{{- if .Values.environment_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backstage.fullname" . }}
  labels:
{{ include "backstage.labels" . | indent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.environment_secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}

